image:
  - Visual Studio 2022
  - Ubuntu
  - macOS #until I understant what is the error on AppVeyor CI

version: 6.0.0-preview-05-{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run -f net7.0 -c Release -p:DevMode=false --project test/DryIoc.TestsRunner

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
