image:
  - Visual Studio 2022
  - Ubuntu
  - macOS

version: 6.0.0-preview-05-{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet test -f:net7.0 -c:Release test/DryIoc.UnitTests
  - dotnet test -f:net7.0 -c:Release test/DryIoc.IssuesTests
  - dotnet test -f:net7.0 -c:Release test/DryIoc.CommonServiceLocator.UnitTests
  - dotnet test -f:net7.0 -c:Release test/DryIoc.Microsoft.DependencyInjection.Specification.Tests
  - dotnet test -f:net7.0 -c:Release docs/DryIoc.Docs

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
